### ISSUE TITLE
License clarifications

### ISSUE THREAD

**Issue by lamba92** [korlibs/korlibs-crypto#3]
The [link](https://github.com/korlibs/korlibs-crypto/blob/f85713257954e6cfcf73cae98faef62075a0e8e0/build.gradle.kts#L553) added in the published pom seems to incorrect. Additionally, there is no license in this repository. Would it be possible to change the link to the actual license and copy such license in the root of this repository?

**Comment by soywiz** [comment]
It was moved from several places. I believe this library was public domain, CC0. All the libraries are at least MIT / Apache 2.0 dual licensed. And some are public domain CC0

**Comment by soywiz** [comment]
It is MIT:
https://github.com/korlibs/korlibs4/blob/backup/krypto/LICENSE
https://github.com/korlibs/korlibs4/blob/backup/LICENSE
